FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    curl \
    git \
    xz-utils \
    && rm -rf /var/lib/apt/lists/*

# Install proto
RUN curl -fsSLO https://moonrepo.dev/install/proto.sh  && \
    chmod +x proto.sh && \
    ./proto.sh --shell=bash --yes && \
    rm -f proto.sh

WORKDIR /workspace
