### Crafted with love by the Loft Orbital team and contributors.
### Licensed under the Apache License, Version 2.0.

fileGroups:
  sources:
    - '**/*.sh'

tasks:
  lint:
    platform: system
    command: shellcheck @files(sources)
    inputs:
      - '@group(sources)'
