tasks:
  gen:
    command:
      - '$workspaceRoot/tools/buildsystem/gen_cue.sh'
      - '$project'
    env:
      K8S_VERSION: '1.28'
    inputs:
      - /tools/buildsystem/gen_cue.sh
    outputs:
      - cue.mod/gen/**/*

  vendor:
    command:
      - '$workspaceRoot/tools/buildsystem/vendor_cue.sh'
      - '$project'
    deps:
      - '^:build'
    inputs:
      - /tools/buildsystem/vendor_cue.sh
    outputs:
      - cue.mod/pkg/**/*

  init:
    command: noop
    deps:
      - '~:vendor'
      - '~:gen'

  vet:
    command: '$workspaceRoot/tools/buildsystem/timoni_vet.sh'
    deps:
      - '~:init'
    inputs:
      - '/tools/buildsystem/timoni_vet.sh'
      - '@group(sources)'

  release:
    command:
      - '$workspaceRoot/tools/buildsystem/release-module.sh'
      - '$project'
    local: true # do not run with `moon check` or `moon ci`
    deps:
      - '^:release'
      - '~:init'
    inputs:
      - 'group(sources)'
      - /tools/buildsystem/release-module.sh
