### Crafted with love by the Loft Orbital team and contributors.
### Licensed under the Apache License, Version 2.0.

fileGroups:
  sources:
    - '*.cue'
    - 'instance/**/*.cue'
    - 'pkg/**/*.cue'
    - 'templates/**/*.cue'
    - 'examples/**/*.cue'

tasks:
  fmt:
    command: cue fmt ./...
    inputs:
      - '@group(sources)'
