on:
  workflow_call:

jobs:
  moonci:
    name: moon ci 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Setup
      - name: Setup Moon
        uses: moonrepo/setup-moon-action@v1
      - name: Setup CUE
        uses: cue-lang/setup-cue@v1.0.0
      - name: Setup Timoni
        uses: stefanprodan/timoni/actions/setup@main
        with:
          version: latest
      - name: Setup shellcheck
        run: sudo snap install shellcheck
      # Run
      - run: moon ci
