name: pull request

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Setup
      - name: Setup Toolchain
        uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true
      - name: Setup shellcheck
        run: sudo snap install shellcheck
      # Run
      - run: moon ci

  commits:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - name: Commitsar check
          uses: aevea/commitsar@v0.20.2
